### ISSUE TITLE
Obfuscation artifacts remain

### ISSUE THREAD

**Issue by HammerBob** [ViRb3/de4dot-cex#6]
de4dot-cex successfully removed most of the ConfuserEx 1.0.0 protection for me, but some artifacts remain in the code. I'm willing to pay if you are willing to improve de4dot-cex to remove these artifacts.
Are you interested?

**Comment by ViRb3** [comment]
Are you sure it is vanilla ConfuserEx (no modifications)? If yes, then please send me the file.

**Comment by HammerBob** [comment]
I'm sure it is vanilla ConfuserEx v1.0.0. My test program is in
de4dot-dex-issue.zip.

You can download the zip
<https://www.zipshare.com/fileDownload/eyJhcmNoaXZlSWQiOiJhNTAxMDljYi1iY2U0LTRjZjQtYjc0OC1kMTI4MTU1ZjM0NTgiLCJlbWFpbCI6ImJvYkBwcXN5c3RlbXMuY29tIn0=>
from:

https://www.zipshare.com/fileDownload/eyJhcmNoaXZlSWQiOiJhNTAxMDljYi1iY2U0LTRjZjQtYjc0OC1kMTI4MTU1ZjM0NTgiLCJlbWFpbCI6ImJvYkBwcXN5c3RlbXMuY29tIn0=
.

Please see de4dot-cex issue.pdf in the zip.

Thanks for looking into this.

**Comment by ViRb3** [comment]
Thanks for the detailed description! The issue is that methods are not inlined after their proxies are resolved. I will see what I can do about that :)

**Comment by ViRb3** [comment]
I implemented de4dot's default `MethodCallInliner`. Note that inlining of instance methods has not been enabled, since I couldn't find that functionality in the test cases you sent me. Please give it a test yourself and let me know if everything is working properly:
https://ci.appveyor.com/project/ViRb3/de4dot-cex/builds/24273228/artifacts

**Comment by HammerBob** [comment]
The issue I identified seems to be working properly now. Thanks a lot!

I'm not sure if I need "inlining of instance methods" working or not. Can
you give me an example of what that looks like in the code? I still see
lots of methods with names like method_N or smethod_N. I'm not sure if some
of those might go away if "inlining of instance methods" was working.

I would like to move our conversation to email. Please email me at:
de4dot-xyzzy@yahoo.com.

**Comment by HammerBob** [comment]
I discovered an issue where "Name" protection is not properly deobfuscated
in one case.

Please refer to the PDF in:

https://www.zipshare.com/fileDownload/eyJhcmNoaXZlSWQiOiIyNzg4OTBjZS0yN2JkLTQ3ZGQtYmZiOC03YWU2MmI1MDZhMDQiLCJlbWFpbCI6ImJvYkBwcXN5c3RlbXMuY29tIn0=

**Comment by ViRb3** [comment]
I will check this when I get back to my laptop. It should be a week or so.

**Comment by danyhm** [comment]
Hello,

Are you still working on this? I also found that some artifacts remain on dotfuscator.

can you please take a look at it ?

https://mega.nz/file/E4whWYJZ#1pGSSouGy2ykfTb2iql_An1cYG3deySjo89f1o0h4CI

**Comment by ViRb3** [comment]
Sorry, I don't think I'll have time to maintain this project in the foreseeable future.

**Comment by HammerBob** [comment]
Hi,

No, I'm not dealing with this any longer.

Bob
